### ISSUE TITLE
Support for datatypes

### ISSUE THREAD

**Issue by wenkesj** [reneweb/react-native-tensorflow#1]
I would like to spec out support for datatypes other than `double`. 

For instance, the following would be a data type choice.
```cpp
tensorflow::Tensor input_data(tensorflow::DT_INT32, shape);
```

Through `tf.feed` or `tf.feedWithDims` there could be a dtype option
```js
tf.feed(...args, 'int32');
```

**Comment by reneweb** [comment]
Hey, that makes sense to me. The default should be a double as it works well with the standard js number, but as a additional optional parameter the user might pass the data type explicitly like you suggested, then we need to pass to iOS & Android, convert to the tensorflow data type and pass to the respective functions.

**Comment by wenkesj** [comment]
@reneweb So a few things that could be some considerations for the API that makes things a lot easier (a small example):

1. Feeding values: 
```js
      const feedDict = {
        input: {
          data: sentence,
          shape: [batchSize, seqLen],
          dtype: 'int32',
        },
        target_sequence_length: {
          data: seqTar,
          shape: [batchSize],
          dtype: 'int32',
        },
        source_sequence_length: {
          data: seqTar,
          shape: [batchSize],
          dtype: 'int32',
        }
      };

      this.tf.feed(feedDict);
```
So each value would have a string key and an object with data, shape and dtype (as in numpy or tf).

2. Theres a HUGE performance loss "transferring memory" to Native methods, more specifically converting `ReadableArrays` to actual Native data. In other words, there's really no current method in RN JS to create a shared array as in NodeJS (`TypedArrayContents`, etc.). I'm lead to understand Expo has their very own fancy `JavaScriptCore.h` C APIs for shared memory, but I have yet to look into it. The way I see things going without a performance loss, data needs to be "created" and "maintained" in Native "memory":
```js
const myTensor = new Float32ArrayNative(SIZE)
// ... and behind the scenes ...
float32 *data = malloc(...)
// ... this is managed through the JavaScriptCore or some heap-like engine
HEAP[newkey] = data
// This way, we don't have to "transfer" data, instead using a key-like mechanism
// possibly linking the GC for RN to this HEAP or something.
```
and interfacing with natural device drivers wouldn't be hard, as you can simply alloc, realloc, move, copy all in native code, so no more round trip (it's all hypothetical) and leaves the UI thread handling what it's supposed to, instead of serializing data back and forth. Accessing would inevitibly have be a Promise/async system, so iterating over data in JS would be SLOW (but hardly EVER necessary).

I know this is out there and a lot of work, but since there's not solid shared data system (that I know of), I think this would be necessary for interfacing with O(N*N*N) arrays (Images and whatnot, for instance Native Camera/Video interfaces)

**Comment by reneweb** [comment]
Thanks for the feedback:
1. Currently I am pretty much copying the android inference interface, however, I agree that it would be sensible to follow the python api & this is something I will look at soonish.

2. I am aware that this is pretty ineffienct & that we need to solve that in order to make this library really useful. The apporach you describe is definetly something to look at - I was also thinking about keeping the data completely on native side and only exposing a set of interfaces to do common transformations on that data, however, that might restrict the possibility of the data processing to much.
