### ISSUE TITLE
Could this be used with Chatbots?

### ISSUE THREAD

**Issue by xavicolomer** [reneweb/react-native-tensorflow#16]
Hi there!

First, thanks and great work!

Secondly, I was able to train a chatbot and export the graph using protobuf format in Python, by following this tutorials
https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077
https://cole-maclean.github.io/blog/RNN-Based-Subreddit-Recommender-System/

I was wandering if I could use this library to create a local chatbot for mobile.

Is that possible?

**Comment by reneweb** [comment]
Hey,
while it should be possible it is not very advisable to do that in the current state of this library. There is a direct api exposed, which allows to basically interact directly with TensorFlow, but would be quite challenging to implement anything using this api and there are quite a bunch of drawbacks. I hope to add some more dedicated to build chat bots in the future, but this is quite a bit down the road.

**Comment by xavicolomer** [comment]
OK!

Thanks for answering!
