### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by davifelipems** [reneweb/react-native-tensorflow#18]
wrong:
results.forEach(result =>
  console.log(
    results.id, // Id of the result
    results.name, // Name of the result
    results.confidence // Confidence value between 0 - 1
  )
)
right:
results.forEach(result =>
  console.log(
    result.id, // Id of the result
    result.name, // Name of the result
    result.confidence // Confidence value between 0 - 1
  )
)

**Comment by reneweb** [comment]
Good catch - just fixed it
