### ISSUE TITLE
RNTensorFlowInferenceModule not resetable (android)

### ISSUE THREAD

**Issue by ajmssc** [reneweb/react-native-tensorflow#20]
RNTensorFlowInferenceModule is missing a method to reset the context.
I see a method in the file RNTensorflowInference.java to reset the context, and another to get the context, but it's not callable from RNTensorFlowInferenceModule.

Also index.js is missing reset() too. And I didn't check iOS but it might also be missing since it's missing from index.js.

**Comment by ajmssc** [comment]
This results in errors of double feeding tensors when using the direct api.

**Comment by Kekedev** [comment]
I have the same problem on both android and iOS.
I first create a new TensorFlow session with new TensorFlow(/pathToMyModel)
then use the steps feed, run and fetch, but I have to close it first if I want to use a new session.
If I try to feed again data into the same session, it will raise an error "impossible to feed the model twice". 

I agree with the solution of ajmssc and confirm that it happens also on iOS.

**Comment by reneweb** [comment]
So far I was only using the reset function in the image recognition module, not in the inference one. There is no reason though not to add it to the inference one. I've merged your pr #21 and also added the reset function to iOS. The change is in release 0.1.7
