### ISSUE TITLE
Tensorflow dense pose estimation support

### ISSUE THREAD

**Issue by jafar-albadarneh** [reneweb/react-native-tensorflow#30]
Is there any plans to support importing & using tesnorflow dense pose.
I tried to replicate what's in the docs at [tfjs](https://github.com/tensorflow/tfjs-models/tree/master/posenet).

I installed the package `@tensorflow-models/posenet` as well as the `@tensorflow/tfjs@0.11.7`.
then had a simple method to load the posenet model as follows:
```js
componentDidMount() {
    this.loadNet();
  }
  
  async getDensePose()
  {
    const imageScaleFactor = 0.50;
    const flipHorizontal = false;
    const outputStride = 16;
    const net   = await posenet.load();
    const pose = net.estimateSinglePose(
      require('./images/sample.jpg'), 
      imageScaleFactor,
      flipHorizontal,
      outputStride);
    console.log('pose estimation result'+pose);

  }
```

but unfortunately having this error:
`Unhandled JS Exception: No backend found in registry.`

Any idea !
Thanks

**Comment by reneweb** [comment]
sorry for late response  - Haven't looked into supporting this - generally speaking it would be nice to be able to just use tfjs within react native by providing some integration, but not sure how possible that is

**Comment by im-aditya** [comment]
Any chance @jafar-albadarneh you were able to run Posenet in React Native ??
