### ISSUE TITLE
Error: Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Switch' with these attrs.

### ISSUE THREAD

**Issue by narensprinter** [reneweb/react-native-tensorflow#32]
Hi

While using TfImageRecognition  I'm getting following error

Error: Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Switch' with these attrs.

But if i test the model with demo pb file provided by react-native-tensorflow examples its working fine.

**Comment by reneweb** [comment]
sorry for late reply - the model you are using is probably not compatible with the Tensorflow version used in this lib which is unfortunately pretty outdated: https://github.com/reneweb/react-native-tensorflow/issues/26
