### ISSUE TITLE
GraphDef-interpreting binary and generating binary are different

### ISSUE THREAD

**Issue by satvinder-panesar** [reneweb/react-native-tensorflow#33]
What is the version of tensorflow used to generate pb file?

I am using tensorflow version 1.7.1 with react-native-tensorflow version 0.1.8 and getting error as stated in title.

**Comment by shaktalles** [comment]
Same issue here.

**Comment by jazzystring1** [comment]
Someone did a pull request for supporting tensorflow 1.8.0 since it only supports tensorflow 1.3.0. You can check it out.

**Comment by reneweb** [comment]
It is unfortunately not super straightforward to do the update - see my latest comment in the pr #28 and this issue #10
