### ISSUE TITLE
How to load image from local file ?

### ISSUE THREAD

**Issue by phanoophong** [reneweb/react-native-tensorflow#9]
How to load image from local file ?

**Comment by maxkuzmin** [comment]
image: data.path.replace('file://', '') works for me as temp workaround.

**Comment by reneweb** [comment]
If you are using the image recognition API then you should be able to pass the path to the image prop, potentially stripping off the `file://` part at the beginning as described by @maxkuzmin. 
If you are using the "Direct Api" it is quite a bit more complex. To load a file in this case you will want to use a library like `react-native-fs`, load the file as base64 and then convert it to the required format. This has several drawbacks as described here: https://github.com/reneweb/react-native-tensorflow/blob/master/README.md#known-issues (there is currently not a really good way to use the direct api unfortunately)
